### ISSUE TITLE
Missing helper.js file and missing variables

### ISSUE THREAD

**Issue by MarSchlaefer** [learn-co-curriculum/fewpjs-js-fundamentals-arithmetic-lab-old#2]
Missing helper.js file to connect index.js to tests. Readme says that the tests will define global variables, but the variable are not defined in the test file.  #staff

**Comment by drakeltheryuujin** [comment]
@MarSchlaefer 

Thank you for spotting this issue and providing feedback.
We have updated the materials (changed the instructions to be more simplified) and believe your issue to have been resolved in this replacement repo: https://github.com/learn-co-curriculum/fewpjs-js-fundamentals-arithmetic-lab
If you do not believe that this issue has been addressed, please re-open this issue. 💙
